### ISSUE TITLE
Provision to provide the input qubits state

### ISSUE THREAD

**Issue by rsehgal** [rsehgal/barcQ#22]
Currently there is no way to provide the input state of different qubits represented by rows of the grid.
Also these 0 and 1 states must be provided in the toolbox so that the user will drag and drop the required input.

**Implementation idea** : There may be another table with just one column that contains the input state of qubits, which can be dragged from the toolbox and dropped on the div of columns in this.

**Comment by Bhartih** [comment]
By default the input state will be 0 as in IBMQ. If user need to set input to 1, he can apply NOT gate and then proceed forward.

**Comment by Bhartih** [comment]
Closing the issue

**Comment by Bhartih** [comment]
Close

**Comment by rsehgal** [comment]
Closing based on above comments
