### ISSUE TITLE
Drag_drop issue

### ISSUE THREAD

**Issue by Bhartih** [rsehgal/barcQ#34]
1) The element dropped in dropzone should only be dragged within dropzonediv.

2) The number of input(n) >1 gate, check for all the cell to be empty before dropping. It may happen that the n>1 gate requires say 3 cell and only 2 cells are empty.
3) one element cannot be dropped over other. Special case: if the 2 input gate is occupying location row1col1 and row2col1 , then the new element should not be allowed to drop on any of this locations.
4) if n>1 gate is to be dragged within dropzoneDiv, then unmerge the previous div which this gate was occupying before dragging.
5)n>1 input gate is not allowed to be dropped in the row for which the remaining columns are not available. Say your grid is  5X5, you are trying to drop the 2 input gate at last i.e. 5th row , but for this gate 6th row is also required for merging which is not available, then don't allow drop of such gate.

6)Id should be same if the element is dragged within dropZonediv.

7) Since each cell consist of div and within div there is img, therefore while dragging the img within dropzoneDiv, the previous div attributes should be reset. 

**Issue-29 and Issue-30 may be considered as its subtask**
Sub-issue 1 : https://github.com/rsehgal/barcQ/issues/29
Sub-issue 2 : https://github.com/rsehgal/barcQ/issues/30

**Comment by rsehgal** [comment]
Looking at your new branch **bharti/temp**, Is this the correct one.

Few comments:
Drag and drop working nicely
Also able to delete the gate
The only problem is when I create user defined gates then upon gate creation the we get only line but the symbol is missing.
For example if I want to create user defined CNOT gate with 0 line as control bit, and line number 2 as the bit to be controlled, then we are getting only line but the control symbol and Xor symbol that makes up a gate in UI is missing.

May be you would like to have a look

**Comment by rsehgal** [comment]
Merged in master
