### ISSUE TITLE
Not able to create Controlled-Z and Controlled-Phase gate using User defined gate concept

### ISSUE THREAD

**Issue by rsehgal** [rsehgal/barcQ#39]
There is some minor issue because of which we are not able to create Controlled-Z and Controlled-Phase gate using User defined gate concept. After clicking the create button, control symbol remains but the Z or Phase gate image disappears.

This happens because these gates were added later, and the corresponding logic for these gates does not exist in the code. It may be pretty easy to fix.

**Comment by Bhartih** [comment]
Corrected.
Chnages are done In mergeandunmerge.js

**Comment by Bhartih** [comment]
Closed

**Comment by Bhartih** [comment]
close

**Comment by rsehgal** [comment]
It seems, you did changes directly to master.
NOT a good idea, please avoid that in future.
This may result in code break.

I am taking master to the previous state.

May i request you to please create a branch from master, and then add you change push the branch and create the pull request

Once your branch is merge then close the issue

**Comment by rsehgal** [comment]
Revoked the changes implemented in this commit

**Comment by Bhartih** [comment]
Changes done in branch bharti/issue39

**Comment by rsehgal** [comment]
Not able to create conrolled Phase gate
![image](https://user-images.githubusercontent.com/3575995/84341980-130f5b00-abc2-11ea-8899-4084cf3da1d7.png)

Its gives alert message
![image](https://user-images.githubusercontent.com/3575995/84342011-25899480-abc2-11ea-8747-8d3a309d867a.png)

May be you would like to have a look.

**Comment by rsehgal** [comment]
Don't spend time on this.
Its fixed now, and will be merged soon.
