### ISSUE TITLE
addtion of 3, 4

### ISSUE THREAD

**Issue by Garima-lab-a11y** [rsehgal/barcQ#86]
![image](https://user-images.githubusercontent.com/72012183/101125466-51d91780-361f-11eb-907c-dd57db19d6c8.png)

**Comment by rsehgal** [comment]
Hi Garima,
I believe you are trying to do 1 + 3, 
May i know what output are you getting. 
Are you getting **10011** as the output

It will be nice if you also upload the resultant histogram.

**Comment by rsehgal** [comment]
My mistake,
You are correctly adding 3 + 4, 
and the output should **111 100**.

Since its not an issue, its just a discussion and hence should be the part of https://github.com/rsehgal/barcQ/issues/69 
hence closing it.

T
